#!/usr/bin/env bash

VERSION=$(cat VERSION)

publish() {
  build
  package
  release
}


build() {
  mkdir -p dist
  go build -o dist/gnote
}

package() {
  tar zcvf macos.tar.gz -C dist  .
}


release() {
  github-release --verbose upload --user gutenye --repo gnote --tag $VERSION --name macos.tar.gz --file macos.tar.gz
}

build-all() {
  ./build.sh
}

case "$1" in
  publish ) publish ;;
  build ) build ;;
  release ) release ;;
  build-all ) build-all ;;
esac
